#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

# Remove surface and features
rm -f constant/triSurface/*.eMesh
rm -rf constant/extendedFeatureEdgeMesh

# Remove specific control dictionary
rm -f system/controlDict
rm -f system/fvSchemes
rm -f system/fvSolution

# Remove added dictionaries
rm -f system/blockMeshDict
rm -f system/decomposeParDict
rm -f 0.orig/include/initialConditions

#------------------------------------------------------------------------------
